"use client";

import { useState, useEffect } from "react";
import { Receipt, Printer, Download } from "lucide-react";

function fmt(n: number) {
  return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);
}

export default function ReceiptsPage() {
  const [payments, setPayments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/payments")
      .then((r) => r.json())
      .then(setPayments)
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const paymentsWithReceipt = payments.filter((p) => p.receiptNumber);

  function printReceipt(p: any) {
    const w = window.open("", "_blank", "width=400,height=600");
    if (!w) return;
    w.document.write(`
      <html><head><title>Receipt ${p.receiptNumber}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; font-size: 13px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 15px; }
        .row { display: flex; justify-content: space-between; padding: 4px 0; }
        .label { color: #666; }
        .total { font-size: 18px; font-weight: bold; border-top: 2px solid #333; padding-top: 10px; margin-top: 10px; }
        .footer { margin-top: 30px; text-align: center; color: #999; font-size: 11px; }
      </style></head><body>
        <div class="header">
          <h2>PG MANAGER</h2>
          <p>Payment Receipt</p>
        </div>
        <div class="row"><span class="label">Receipt No</span><span>${p.receiptNumber}</span></div>
        <div class="row"><span class="label">Date</span><span>${new Date(p.date).toLocaleDateString("en-IN")}</span></div>
        <hr>
        <div class="row"><span class="label">Tenant</span><span>${p.tenantName}</span></div>
        <div class="row"><span class="label">Month</span><span>${p.rentMonth}</span></div>
        <hr>
        <div class="total row"><span>Amount Paid</span><span>${fmt(p.amount)}</span></div>
        <div class="row"><span class="label">Method</span><span>${p.method?.replace("_", " ")}</span></div>
        ${p.transactionId ? `<div class="row"><span class="label">Transaction ID</span><span>${p.transactionId}</span></div>` : ""}
        <div class="footer">
          <p>Generated by PG Manager</p>
          <p>${new Date().toLocaleString("en-IN")}</p>
        </div>
      </body></html>
    `);
    w.document.close();
    w.print();
  }

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl font-bold">Receipts</h1>
        <p className="text-sm text-muted-foreground">{paymentsWithReceipt.length} receipts generated</p>
      </div>

      <div className="bg-card border rounded-xl overflow-hidden">
        {loading ? (
          <div className="p-8 text-center text-muted-foreground">Loading…</div>
        ) : paymentsWithReceipt.length === 0 ? (
          <div className="p-8 text-center text-muted-foreground">
            <Receipt className="w-12 h-12 mx-auto mb-3 opacity-30" />
            <p>No receipts yet</p>
            <p className="text-sm mt-1">Receipts are generated automatically when payments are recorded</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-xs text-muted-foreground border-b bg-muted/50">
                  <th className="px-4 py-3 font-medium">Receipt #</th>
                  <th className="px-4 py-3 font-medium">Tenant</th>
                  <th className="px-4 py-3 font-medium">Amount</th>
                  <th className="px-4 py-3 font-medium">Month</th>
                  <th className="px-4 py-3 font-medium">Date</th>
                  <th className="px-4 py-3 font-medium">Actions</th>
                </tr>
              </thead>
              <tbody>
                {paymentsWithReceipt.map((p) => (
                  <tr key={p.id} className="border-b last:border-0 hover:bg-muted/30">
                    <td className="px-4 py-3 font-mono text-xs">{p.receiptNumber}</td>
                    <td className="px-4 py-3 font-medium">{p.tenantName}</td>
                    <td className="px-4 py-3 font-medium">{fmt(p.amount)}</td>
                    <td className="px-4 py-3 text-muted-foreground">{p.rentMonth}</td>
                    <td className="px-4 py-3">{new Date(p.date).toLocaleDateString("en-IN")}</td>
                    <td className="px-4 py-3">
                      <button onClick={() => printReceipt(p)}
                        className="inline-flex items-center gap-1 text-xs text-primary hover:underline">
                        <Printer className="w-3 h-3" /> Print
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
